backend:
  name: git-gateway
  branch: master

media_folder: "public/images"
public_folder: "/images"
format: 'text'

collections:
  - name: "navbar"
    label: "Navbar"
    folder: "src/components"
    create: true
    fields:
    - { name: 'title', label: 'Title', widget: 'string' }
    - { name: 'body', label: 'Body', widget: 'text' }
    - { name: 'excerpt', label: 'Excerpt', widget: 'text' }
    - { name: 'date', label: 'Date', widget: 'datetime' }
