backend:
  name: git-gateway

media_folder: static/images
public_folder: /images

collections:
  - name: "home"
    label: "Home"
    files:
      - file: "src/components/Home/Home.md"
        label: "Home"
        fields:
          - { name: "image", label: "Image", widget: "image" }
          - { name: "content", label: "Content", widget: "markdown" }
