backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "navbar"
    label: "Navbar"
    folder: "src/components"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "link", label: "Link", widget: "string" }
